"""- Add DPP and it's related models

Revision ID: 1fcd433b0aff
Revises: cd7c0666ca86
Create Date: 2025-12-15 23:39:42.966773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1fcd433b0aff'
down_revision: Union[str, Sequence[str], None] = 'cd7c0666ca86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digitalproductpassport',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('public_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'SUSPENDED', 'ARCHIVED', name='dppstatus'), nullable=False),
    sa.Column('qr_code_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('blockchain_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_digitalproductpassport_public_uid'), 'digitalproductpassport', ['public_uid'], unique=True)
    op.create_table('dppevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dpp_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'PUBLISHED', 'UPDATED', 'SCANNED', 'STATUS_CHANGE', 'OWNERSHIP_TRANSFER', name='dppeventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dpp_id'], ['digitalproductpassport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dppevent_dpp_id'), 'dppevent', ['dpp_id'], unique=False)
    op.create_table('dppextradetail',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dpp_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dpp_id'], ['digitalproductpassport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dppextradetail_key'), 'dppextradetail', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dppextradetail_key'), table_name='dppextradetail')
    op.drop_table('dppextradetail')
    op.drop_index(op.f('ix_dppevent_dpp_id'), table_name='dppevent')
    op.drop_table('dppevent')
    op.drop_index(op.f('ix_digitalproductpassport_public_uid'), table_name='digitalproductpassport')
    op.drop_table('digitalproductpassport')
    # ### end Alembic commands ###
