"""initial commit

Revision ID: 32659ce6b0f6
Revises: 
Create Date: 2026-01-11 21:14:08.176836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32659ce6b0f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_key'), 'permission', ['key'], unique=True)
    op.create_table('tenant',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('BRAND', 'SUPPLIER', 'SYSTEM_ADMIN', name='tenanttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'ARCHIVED', name='tenantstatus'), nullable=False),
    sa.Column('location_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=False)
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('certificatedefinition',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issuer_authority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('ENVIRONMENTAL', 'SOCIAL', 'CHEMICAL_SAFETY', 'ORIGIN', 'GOVERNANCE', 'QUALITY', 'OTHER', name='certificatecategory'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificatedefinition_name'), 'certificatedefinition', ['name'], unique=False)
    op.create_table('dpptemplate',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('source_template_id', sa.Uuid(), nullable=True),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sa.Enum('GENERIC', 'APPAREL', 'FOOTWEAR', 'ELECTRONICS', 'LUXURY', 'MINIMALIST', 'DATA_HEAVY', name='templatecategory'), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('layout_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_css', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_template_id'], ['dpptemplate.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dpptemplate_layout', 'dpptemplate', ['layout_config'], unique=False, postgresql_using='gin')
    op.create_index('idx_dpptemplate_style', 'dpptemplate', ['style_config'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_dpptemplate_is_deleted'), 'dpptemplate', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dpptemplate_name'), 'dpptemplate', ['name'], unique=False)
    op.create_table('materialdefinition',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('material_type', sa.Enum('SYNTHETIC', 'NATURAL', 'BLEND', 'RECYCLED', 'METAL', 'OTHER', name='materialtype'), nullable=False),
    sa.Column('default_carbon_footprint', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ean', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('internal_erp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lifecycle_status', sa.Enum('ACTIVE', 'DISCONTINUED', 'END_OF_SUPPORT', 'PRE_RELEASE', name='productlifecyclestatus'), nullable=False),
    sa.Column('main_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_ean'), 'product', ['ean'], unique=False)
    op.create_index(op.f('ix_product_internal_erp_id'), 'product', ['internal_erp_id'], unique=False)
    op.create_index(op.f('ix_product_lifecycle_status'), 'product', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    op.create_index(op.f('ix_product_upc'), 'product', ['upc'], unique=False)
    op.create_table('role',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.create_table('supplierartifact',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', 'CERTIFICATE', 'AUDIT_REPORT', 'OTHER', name='artifacttype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplierprofile',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('connected_tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['connected_tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplierprofile_connected_tenant_id'), 'supplierprofile', ['connected_tenant_id'], unique=False)
    op.create_index(op.f('ix_supplierprofile_location_country'), 'supplierprofile', ['location_country'], unique=False)
    op.create_index(op.f('ix_supplierprofile_tenant_id'), 'supplierprofile', ['tenant_id'], unique=False)
    op.create_table('systemauditlog',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'SOFT_DELETE', 'PUBLISH', 'LOGIN', 'DOWNLOAD', name='auditaction'), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemauditlog_actor_user_id'), 'systemauditlog', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_systemauditlog_entity_id'), 'systemauditlog', ['entity_id'], unique=False)
    op.create_index(op.f('ix_systemauditlog_entity_type'), 'systemauditlog', ['entity_type'], unique=False)
    op.create_index(op.f('ix_systemauditlog_tenant_id'), 'systemauditlog', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_systemauditlog_timestamp'), 'systemauditlog', ['timestamp'], unique=False)
    op.create_table('dpp',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('public_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qr_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qr_style_config', sa.JSON(), nullable=False),
    sa.Column('default_dpp_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DRAFT_CONTAINER', 'SUSPENDED', 'RECALLED', 'DECOMMISSIONED', name='dpplifecyclestatus'), nullable=False),
    sa.Column('total_scans', sa.Integer(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_dpp_version_id'], ['dppversion.id'], name='fk_dpp_default_version', use_alter=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dpp_is_deleted'), 'dpp', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dpp_product_id'), 'dpp', ['product_id'], unique=True)
    op.create_index(op.f('ix_dpp_public_uid'), 'dpp', ['public_uid'], unique=True)
    op.create_index(op.f('ix_dpp_tenant_id'), 'dpp', ['tenant_id'], unique=False)
    op.create_table('dpptemplatefield',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'RICH_TEXT', 'HEADER', 'LABEL', 'NUMBER', 'COLOR', name='templatefieldtype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['dpptemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dpptemplatefield_key'), 'dpptemplatefield', ['key'], unique=False)
    op.create_index(op.f('ix_dpptemplatefield_template_id'), 'dpptemplatefield', ['template_id'], unique=False)
    op.create_table('productmedia',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', 'MODEL_3D', name='mediatype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productmedia_is_deleted'), 'productmedia', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_productmedia_product_id'), 'productmedia', ['product_id'], unique=False)
    op.create_table('productversion',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version_sequence', sa.Integer(), nullable=False),
    sa.Column('version_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='productversionstatus'), nullable=False),
    sa.Column('manufacturing_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mass_kg', sa.Float(), nullable=False),
    sa.Column('total_carbon_footprint', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['supplier_tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productversion_version_sequence'), 'productversion', ['version_sequence'], unique=False)
    op.create_table('rolepermissionlink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('tenantconnection',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_tenant_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_tenant_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_profile_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_email_invite', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invitation_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'SUSPENDED', name='connectionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['brand_tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['supplier_profile_id'], ['supplierprofile.id'], ),
    sa.ForeignKeyConstraint(['supplier_tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_profile_id')
    )
    op.create_index(op.f('ix_tenantconnection_brand_tenant_id'), 'tenantconnection', ['brand_tenant_id'], unique=False)
    op.create_index(op.f('ix_tenantconnection_invitation_token'), 'tenantconnection', ['invitation_token'], unique=True)
    op.create_table('tenantinvitation',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitationstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('inviter_id', sa.Uuid(), nullable=False),
    sa.Column('invitee_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_tenantinvitation_email'), 'tenantinvitation', ['email'], unique=False)
    op.create_table('tenantmember',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'INACTIVE', name='memberstatus'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenantmember_tenant_id'), 'tenantmember', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenantmember_user_id'), 'tenantmember', ['user_id'], unique=False)
    op.create_table('datacontributionrequest',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('brand_tenant_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_tenant_id', sa.Uuid(), nullable=False),
    sa.Column('initial_version_id', sa.Uuid(), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('request_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'ACCEPTED', 'DECLINED', 'IN_PROGRESS', 'SUBMITTED', 'CHANGES_REQUESTED', 'COMPLETED', name='requeststatus'), nullable=False),
    sa.ForeignKeyConstraint(['brand_tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['tenantconnection.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['productversion.id'], ),
    sa.ForeignKeyConstraint(['initial_version_id'], ['productversion.id'], ),
    sa.ForeignKeyConstraint(['supplier_tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dppaccessrule',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('passport_id', sa.Uuid(), nullable=False),
    sa.Column('rule_type', sa.Enum('GEO_ALLOW', 'GEO_BLOCK', 'PASSWORD', 'TIME_WINDOW', 'IP_WHITELIST', name='accessruletype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rule_config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['passport_id'], ['dpp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dppaccessrule_is_deleted'), 'dppaccessrule', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dppaccessrule_passport_id'), 'dppaccessrule', ['passport_id'], unique=False)
    op.create_table('dppversion',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('passport_id', sa.Uuid(), nullable=False),
    sa.Column('source_product_version_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='dppversionstatus'), nullable=False),
    sa.Column('change_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('meta_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_share_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['passport_id'], ['dpp.id'], ),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['source_product_version_id'], ['productversion.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['dpptemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dppversion_is_deleted'), 'dppversion', ['is_deleted'], unique=False)
    op.create_table('productversionartifact',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('source_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_hash_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', 'CERTIFICATE', 'AUDIT_REPORT', 'OTHER', name='artifacttype'), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['supplierartifact.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['productversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productversionartifact_file_hash_sha256'), 'productversionartifact', ['file_hash_sha256'], unique=False)
    op.create_index(op.f('ix_productversionartifact_is_deleted'), 'productversionartifact', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_productversionartifact_version_id'), 'productversionartifact', ['version_id'], unique=False)
    op.create_table('productversioncertificate',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('certificate_type_id', sa.Uuid(), nullable=False),
    sa.Column('source_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('snapshot_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_issuer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issuer_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issuer_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('was_valid_at_submission', sa.Boolean(), nullable=False),
    sa.Column('compliance_check_timestamp', sa.DateTime(), nullable=False),
    sa.Column('file_hash_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_type_id'], ['certificatedefinition.id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['supplierartifact.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['productversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productversioncertificate_version_id'), 'productversioncertificate', ['version_id'], unique=False)
    op.create_table('productversionmaterial',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('source_material_definition_id', sa.Uuid(), nullable=True),
    sa.Column('material_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('origin_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'RESTRICTED_AUDIT', 'RESTRICTED_RECYCLE', 'INTERNAL', name='visibilityscope'), nullable=False),
    sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['productversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productversionrecycling',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('total_recyclability_percentage', sa.Float(), nullable=False),
    sa.Column('recycling_index_score', sa.Float(), nullable=True),
    sa.Column('recyclability_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('waste_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_action', sa.Enum('RECYCLE', 'REUSE', 'COMPOST', 'RETURN_TO_BRAND', 'SPECIAL_HANDLING', 'LANDFILL', name='recyclingaction'), nullable=False),
    sa.Column('is_hazardous', sa.Boolean(), nullable=False),
    sa.Column('collection_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_disassembly_time_minutes', sa.Integer(), nullable=True),
    sa.Column('general_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('safety_warning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['productversion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    op.create_index(op.f('ix_productversionrecycling_is_deleted'), 'productversionrecycling', ['is_deleted'], unique=False)
    op.create_table('productversionsupplynode',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['productversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaborationcomment',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_rejection_reason', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['datacontributionrequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborationcomment_request_id'), 'collaborationcomment', ['request_id'], unique=False)
    op.create_table('dpproutinglogic',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('passport_id', sa.Uuid(), nullable=False),
    sa.Column('target_version_id', sa.Uuid(), nullable=False),
    sa.Column('condition_country_codes', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passport_id'], ['dpp.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['dppversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dpproutinglogic_is_deleted'), 'dpproutinglogic', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dpproutinglogic_passport_id'), 'dpproutinglogic', ['passport_id'], unique=False)
    op.create_table('dppversionlocalization',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['dppversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dppversionlocalization_is_deleted'), 'dppversionlocalization', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dppversionlocalization_version_id'), 'dppversionlocalization', ['version_id'], unique=False)
    op.create_table('productversionrecyclingstage',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recycling_info_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recycling_info_id'], ['productversionrecycling.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productversionrecyclingstage_is_deleted'), 'productversionrecyclingstage', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_productversionrecyclingstage_recycling_info_id'), 'productversionrecyclingstage', ['recycling_info_id'], unique=False)
    op.create_table('dpplocalizationentry',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('localization_id', sa.Uuid(), nullable=False),
    sa.Column('template_field_id', sa.Uuid(), nullable=False),
    sa.Column('translated_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['localization_id'], ['dppversionlocalization.id'], ),
    sa.ForeignKeyConstraint(['template_field_id'], ['dpptemplatefield.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dpplocalizationentry_localization_id'), 'dpplocalizationentry', ['localization_id'], unique=False)
    op.create_index(op.f('ix_dpplocalizationentry_template_field_id'), 'dpplocalizationentry', ['template_field_id'], unique=False)
    op.create_table('productversionrecyclingstagecontent',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT_BLOCK', 'IMAGE', 'VIDEO', 'DOCUMENT', 'WARNING_BLOCK', name='stagecontenttype'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('text_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_size_mb', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['productversionrecyclingstage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productversionrecyclingstagecontent_is_deleted'), 'productversionrecyclingstagecontent', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_productversionrecyclingstagecontent_stage_id'), 'productversionrecyclingstagecontent', ['stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productversionrecyclingstagecontent_stage_id'), table_name='productversionrecyclingstagecontent')
    op.drop_index(op.f('ix_productversionrecyclingstagecontent_is_deleted'), table_name='productversionrecyclingstagecontent')
    op.drop_table('productversionrecyclingstagecontent')
    op.drop_index(op.f('ix_dpplocalizationentry_template_field_id'), table_name='dpplocalizationentry')
    op.drop_index(op.f('ix_dpplocalizationentry_localization_id'), table_name='dpplocalizationentry')
    op.drop_table('dpplocalizationentry')
    op.drop_index(op.f('ix_productversionrecyclingstage_recycling_info_id'), table_name='productversionrecyclingstage')
    op.drop_index(op.f('ix_productversionrecyclingstage_is_deleted'), table_name='productversionrecyclingstage')
    op.drop_table('productversionrecyclingstage')
    op.drop_index(op.f('ix_dppversionlocalization_version_id'), table_name='dppversionlocalization')
    op.drop_index(op.f('ix_dppversionlocalization_is_deleted'), table_name='dppversionlocalization')
    op.drop_table('dppversionlocalization')
    op.drop_index(op.f('ix_dpproutinglogic_passport_id'), table_name='dpproutinglogic')
    op.drop_index(op.f('ix_dpproutinglogic_is_deleted'), table_name='dpproutinglogic')
    op.drop_table('dpproutinglogic')
    op.drop_index(op.f('ix_collaborationcomment_request_id'), table_name='collaborationcomment')
    op.drop_table('collaborationcomment')
    op.drop_table('productversionsupplynode')
    op.drop_index(op.f('ix_productversionrecycling_is_deleted'), table_name='productversionrecycling')
    op.drop_table('productversionrecycling')
    op.drop_table('productversionmaterial')
    op.drop_index(op.f('ix_productversioncertificate_version_id'), table_name='productversioncertificate')
    op.drop_table('productversioncertificate')
    op.drop_index(op.f('ix_productversionartifact_version_id'), table_name='productversionartifact')
    op.drop_index(op.f('ix_productversionartifact_is_deleted'), table_name='productversionartifact')
    op.drop_index(op.f('ix_productversionartifact_file_hash_sha256'), table_name='productversionartifact')
    op.drop_table('productversionartifact')
    op.drop_index(op.f('ix_dppversion_is_deleted'), table_name='dppversion')
    op.drop_table('dppversion')
    op.drop_index(op.f('ix_dppaccessrule_passport_id'), table_name='dppaccessrule')
    op.drop_index(op.f('ix_dppaccessrule_is_deleted'), table_name='dppaccessrule')
    op.drop_table('dppaccessrule')
    op.drop_table('datacontributionrequest')
    op.drop_index(op.f('ix_tenantmember_user_id'), table_name='tenantmember')
    op.drop_index(op.f('ix_tenantmember_tenant_id'), table_name='tenantmember')
    op.drop_table('tenantmember')
    op.drop_index(op.f('ix_tenantinvitation_email'), table_name='tenantinvitation')
    op.drop_table('tenantinvitation')
    op.drop_index(op.f('ix_tenantconnection_invitation_token'), table_name='tenantconnection')
    op.drop_index(op.f('ix_tenantconnection_brand_tenant_id'), table_name='tenantconnection')
    op.drop_table('tenantconnection')
    op.drop_table('rolepermissionlink')
    op.drop_index(op.f('ix_productversion_version_sequence'), table_name='productversion')
    op.drop_table('productversion')
    op.drop_index(op.f('ix_productmedia_product_id'), table_name='productmedia')
    op.drop_index(op.f('ix_productmedia_is_deleted'), table_name='productmedia')
    op.drop_table('productmedia')
    op.drop_index(op.f('ix_dpptemplatefield_template_id'), table_name='dpptemplatefield')
    op.drop_index(op.f('ix_dpptemplatefield_key'), table_name='dpptemplatefield')
    op.drop_table('dpptemplatefield')
    op.drop_index(op.f('ix_dpp_tenant_id'), table_name='dpp')
    op.drop_index(op.f('ix_dpp_public_uid'), table_name='dpp')
    op.drop_index(op.f('ix_dpp_product_id'), table_name='dpp')
    op.drop_index(op.f('ix_dpp_is_deleted'), table_name='dpp')
    op.drop_table('dpp')
    op.drop_index(op.f('ix_systemauditlog_timestamp'), table_name='systemauditlog')
    op.drop_index(op.f('ix_systemauditlog_tenant_id'), table_name='systemauditlog')
    op.drop_index(op.f('ix_systemauditlog_entity_type'), table_name='systemauditlog')
    op.drop_index(op.f('ix_systemauditlog_entity_id'), table_name='systemauditlog')
    op.drop_index(op.f('ix_systemauditlog_actor_user_id'), table_name='systemauditlog')
    op.drop_table('systemauditlog')
    op.drop_index(op.f('ix_supplierprofile_tenant_id'), table_name='supplierprofile')
    op.drop_index(op.f('ix_supplierprofile_location_country'), table_name='supplierprofile')
    op.drop_index(op.f('ix_supplierprofile_connected_tenant_id'), table_name='supplierprofile')
    op.drop_table('supplierprofile')
    op.drop_table('supplierartifact')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_product_upc'), table_name='product')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_index(op.f('ix_product_lifecycle_status'), table_name='product')
    op.drop_index(op.f('ix_product_internal_erp_id'), table_name='product')
    op.drop_index(op.f('ix_product_ean'), table_name='product')
    op.drop_table('product')
    op.drop_table('materialdefinition')
    op.drop_index(op.f('ix_dpptemplate_name'), table_name='dpptemplate')
    op.drop_index(op.f('ix_dpptemplate_is_deleted'), table_name='dpptemplate')
    op.drop_index('idx_dpptemplate_style', table_name='dpptemplate', postgresql_using='gin')
    op.drop_index('idx_dpptemplate_layout', table_name='dpptemplate', postgresql_using='gin')
    op.drop_table('dpptemplate')
    op.drop_index(op.f('ix_certificatedefinition_name'), table_name='certificatedefinition')
    op.drop_table('certificatedefinition')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_permission_key'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
