"""initial commit

Revision ID: 3541736db17b
Revises: 
Create Date: 2026-01-04 00:04:47.866734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3541736db17b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_key'), 'permission', ['key'], unique=True)
    op.create_table('tenant',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('BRAND', 'SUPPLIER', 'HYBRID', name='tenanttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'ARCHIVED', name='tenantstatus'), nullable=False),
    sa.Column('location_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=False)
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('certification',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issuer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certification_code'), 'certification', ['code'], unique=True)
    op.create_index(op.f('ix_certification_name'), 'certification', ['name'], unique=False)
    op.create_table('material',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('material_type', sa.Enum('COTTON', 'POLYESTER', 'NYLON', 'WOOL', 'VISCOSE', 'BLEND', 'OTHER', name='materialtype'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_code'), 'material', ['code'], unique=True)
    op.create_index(op.f('ix_material_name'), 'material', ['name'], unique=False)
    op.create_table('product',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gtin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    op.create_index(op.f('ix_product_tenant_id'), 'product', ['tenant_id'], unique=False)
    op.create_table('role',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.create_table('supplierprofile',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('connected_tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['connected_tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productversion',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('version_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WORKING_DRAFT', 'SUBMITTED', 'REVISION_REQUIRED', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='versionstatus'), nullable=False),
    sa.Column('created_by_tenant_id', sa.Uuid(), nullable=False),
    sa.Column('change_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manufacturing_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_carbon_footprint_kg', sa.Float(), nullable=True),
    sa.Column('total_water_usage_liters', sa.Float(), nullable=True),
    sa.Column('total_energy_mj', sa.Float(), nullable=True),
    sa.Column('recycling_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recyclability_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['productversion.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productversion_product_id'), 'productversion', ['product_id'], unique=False)
    op.create_table('rolepermissionlink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sparepart',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordering_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplierfacilitycertification',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_profile_id'], ['supplierprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenantconnection',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_tenant_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_tenant_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_profile_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_email_invite', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invitation_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONNECTED', 'DECLINED', 'DISCONNECTED', name='connectionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['brand_tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['supplier_profile_id'], ['supplierprofile.id'], ),
    sa.ForeignKeyConstraint(['supplier_tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_profile_id')
    )
    op.create_index(op.f('ix_tenantconnection_brand_tenant_id'), 'tenantconnection', ['brand_tenant_id'], unique=False)
    op.create_index(op.f('ix_tenantconnection_invitation_token'), 'tenantconnection', ['invitation_token'], unique=True)
    op.create_table('tenantinvitation',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', name='invitationstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('inviter_id', sa.Uuid(), nullable=False),
    sa.Column('invitee_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_tenantinvitation_email'), 'tenantinvitation', ['email'], unique=False)
    op.create_table('tenantmember',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='memberstatus'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenantmember_tenant_id'), 'tenantmember', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenantmember_user_id'), 'tenantmember', ['user_id'], unique=False)
    op.create_table('datacontributionrequest',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('brand_tenant_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_tenant_id', sa.Uuid(), nullable=False),
    sa.Column('initial_version_id', sa.Uuid(), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('request_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'ACCEPTED', 'DECLINED', 'IN_PROGRESS', 'SUBMITTED', 'CHANGES_REQUESTED', 'COMPLETED', name='requeststatus'), nullable=False),
    sa.ForeignKeyConstraint(['brand_tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['tenantconnection.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['productversion.id'], ),
    sa.ForeignKeyConstraint(['initial_version_id'], ['productversion.id'], ),
    sa.ForeignKeyConstraint(['supplier_tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digitalproductpassport',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('public_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'SUSPENDED', name='dppstatus'), nullable=False),
    sa.Column('active_version_id', sa.Uuid(), nullable=True),
    sa.Column('qr_code_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('style_config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['active_version_id'], ['productversion.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_digitalproductpassport_public_uid'), 'digitalproductpassport', ['public_uid'], unique=True)
    op.create_index(op.f('ix_digitalproductpassport_tenant_id'), 'digitalproductpassport', ['tenant_id'], unique=False)
    op.create_table('productversionmedia',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['productversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productversionmedia_version_id'), 'productversionmedia', ['version_id'], unique=False)
    op.create_table('versioncertification',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('certification_id', sa.Uuid(), nullable=True),
    sa.Column('document_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['certification_id'], ['certification.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['productversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versioncertification_version_id'), 'versioncertification', ['version_id'], unique=False)
    op.create_table('versionmaterial',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('unlisted_material_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('origin_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('material_carbon_footprint_kg', sa.Float(), nullable=True),
    sa.Column('transport_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['productversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versionmaterial_version_id'), 'versionmaterial', ['version_id'], unique=False)
    op.create_table('versionsupplier',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_profile_id', sa.Uuid(), nullable=True),
    sa.Column('unlisted_supplier_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unlisted_supplier_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('TIER_1_ASSEMBLY', 'TIER_2_FABRIC', 'TIER_3_FIBER', name='supplierrole'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_profile_id'], ['supplierprofile.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['productversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versionsupplier_version_id'), 'versionsupplier', ['version_id'], unique=False)
    op.create_table('collaborationcomment',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_rejection_reason', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['datacontributionrequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborationcomment_request_id'), 'collaborationcomment', ['request_id'], unique=False)
    op.create_table('dppevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('passport_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['passport_id'], ['digitalproductpassport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dppevent_passport_id'), 'dppevent', ['passport_id'], unique=False)
    op.create_table('dppextradetail',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('passport_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passport_id'], ['digitalproductpassport.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dppextradetail_key'), 'dppextradetail', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dppextradetail_key'), table_name='dppextradetail')
    op.drop_table('dppextradetail')
    op.drop_index(op.f('ix_dppevent_passport_id'), table_name='dppevent')
    op.drop_table('dppevent')
    op.drop_index(op.f('ix_collaborationcomment_request_id'), table_name='collaborationcomment')
    op.drop_table('collaborationcomment')
    op.drop_index(op.f('ix_versionsupplier_version_id'), table_name='versionsupplier')
    op.drop_table('versionsupplier')
    op.drop_index(op.f('ix_versionmaterial_version_id'), table_name='versionmaterial')
    op.drop_table('versionmaterial')
    op.drop_index(op.f('ix_versioncertification_version_id'), table_name='versioncertification')
    op.drop_table('versioncertification')
    op.drop_index(op.f('ix_productversionmedia_version_id'), table_name='productversionmedia')
    op.drop_table('productversionmedia')
    op.drop_index(op.f('ix_digitalproductpassport_tenant_id'), table_name='digitalproductpassport')
    op.drop_index(op.f('ix_digitalproductpassport_public_uid'), table_name='digitalproductpassport')
    op.drop_table('digitalproductpassport')
    op.drop_table('datacontributionrequest')
    op.drop_index(op.f('ix_tenantmember_user_id'), table_name='tenantmember')
    op.drop_index(op.f('ix_tenantmember_tenant_id'), table_name='tenantmember')
    op.drop_table('tenantmember')
    op.drop_index(op.f('ix_tenantinvitation_email'), table_name='tenantinvitation')
    op.drop_table('tenantinvitation')
    op.drop_index(op.f('ix_tenantconnection_invitation_token'), table_name='tenantconnection')
    op.drop_index(op.f('ix_tenantconnection_brand_tenant_id'), table_name='tenantconnection')
    op.drop_table('tenantconnection')
    op.drop_table('supplierfacilitycertification')
    op.drop_table('sparepart')
    op.drop_table('rolepermissionlink')
    op.drop_index(op.f('ix_productversion_product_id'), table_name='productversion')
    op.drop_table('productversion')
    op.drop_table('supplierprofile')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_product_tenant_id'), table_name='product')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_material_name'), table_name='material')
    op.drop_index(op.f('ix_material_code'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_certification_name'), table_name='certification')
    op.drop_index(op.f('ix_certification_code'), table_name='certification')
    op.drop_table('certification')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_permission_key'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
