"""made manufacturing_country optional

Revision ID: 3e56b5af9569
Revises: 0bb4481a330c
Create Date: 2026-01-14 21:51:12.472950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e56b5af9569'
down_revision: Union[str, Sequence[str], None] = '0bb4481a330c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productversion', 'manufacturing_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productversion', 'manufacturing_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
