"""Add lineage_id to materials, supply chain, and certificates

Revision ID: 3e708107fd8d
Revises: cb0149bf40d3
Create Date: 2026-02-01 16:30:23.467636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e708107fd8d'
down_revision: Union[str, Sequence[str], None] = 'cb0149bf40d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productversioncertificate', sa.Column('lineage_id', sa.Uuid(), nullable=False, server_default=sa.text('gen_random_uuid()')))
    op.create_index(op.f('ix_productversioncertificate_lineage_id'), 'productversioncertificate', ['lineage_id'], unique=False)
    op.add_column('productversionmaterial', sa.Column('lineage_id', sa.Uuid(), nullable=False, server_default=sa.text('gen_random_uuid()')))
    op.create_index(op.f('ix_productversionmaterial_lineage_id'), 'productversionmaterial', ['lineage_id'], unique=False)
    op.add_column('productversionsupplynode', sa.Column('lineage_id', sa.Uuid(), nullable=False, server_default=sa.text('gen_random_uuid()')))
    op.create_index(op.f('ix_productversionsupplynode_lineage_id'), 'productversionsupplynode', ['lineage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productversionsupplynode_lineage_id'), table_name='productversionsupplynode')
    op.drop_column('productversionsupplynode', 'lineage_id')
    op.drop_index(op.f('ix_productversionmaterial_lineage_id'), table_name='productversionmaterial')
    op.drop_column('productversionmaterial', 'lineage_id')
    op.drop_index(op.f('ix_productversioncertificate_lineage_id'), table_name='productversioncertificate')
    op.drop_column('productversioncertificate', 'lineage_id')
    # ### end Alembic commands ###
