"""add certificate type field

Revision ID: 440d9ed1a45e
Revises: dc98e7b883ec
Create Date: 2026-02-04 22:48:41.181486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '440d9ed1a45e'
down_revision: Union[str, Sequence[str], None] = 'dc98e7b883ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add certificate_type column as nullable first
    op.add_column('productversioncertificate', sa.Column('certificate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Step 2: Backfill existing records with name from CertificateDefinition
    # Use raw SQL to join and update
    op.execute("""
        UPDATE productversioncertificate pvc
        SET certificate_type = cd.name
        FROM certificatedefinition cd
        WHERE pvc.certificate_type_id = cd.id
    """)
    
    # Step 3: For any records that still have NULL (certificate_type_id is NULL or doesn't exist),
    # set a default value. This shouldn't happen in normal operation, but handle it safely.
    op.execute("""
        UPDATE productversioncertificate
        SET certificate_type = 'Unknown Certificate'
        WHERE certificate_type IS NULL
    """)
    
    # Step 4: Now make the column NOT NULL
    op.alter_column(
        'productversioncertificate',
        'certificate_type',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productversioncertificate', 'certificate_type')
    # ### end Alembic commands ###
