"""Add DPP related models

Revision ID: 57c5e9ff06f1
Revises: 50975a90841a
Create Date: 2025-12-10 22:29:37.999298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '57c5e9ff06f1'
down_revision: Union[str, Sequence[str], None] = '50975a90841a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issuer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certification_code'), 'certification', ['code'], unique=True)
    op.create_table('material',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('material_type', sa.Enum('NATURAL', 'SYNTHETIC', 'BLEND', 'SEMI_SYNTHETIC', name='materialtype'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_code'), 'material', ['code'], unique=True)
    op.create_index(op.f('ix_material_name'), 'material', ['name'], unique=False)
    op.create_table('product',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('gtin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manufacturing_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('care_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disposal_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_gtin'), 'product', ['gtin'], unique=False)
    op.create_index(op.f('ix_product_model_reference'), 'product', ['model_reference'], unique=False)
    op.create_index(op.f('ix_product_tenant_id'), 'product', ['tenant_id'], unique=False)
    op.create_table('supplier',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('facility_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_audit_rating', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_location_country'), 'supplier', ['location_country'], unique=False)
    op.create_index(op.f('ix_supplier_tenant_id'), 'supplier', ['tenant_id'], unique=False)
    op.create_table('productcertificationlink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('certification_id', sa.Uuid(), nullable=False),
    sa.Column('certificate_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('digital_document_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['certification_id'], ['certification.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'certification_id')
    )
    op.create_table('productdurability',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('pilling_resistance_grade', sa.Float(), nullable=True),
    sa.Column('color_fastness_grade', sa.Float(), nullable=True),
    sa.Column('dimensional_stability_percent', sa.Float(), nullable=True),
    sa.Column('zipper_durability_cycles', sa.Integer(), nullable=True),
    sa.Column('repairability_score', sa.Float(), nullable=True),
    sa.Column('repair_instructions_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recyclability_class', sa.Enum('CLASS_A', 'CLASS_B', 'CLASS_C', 'CLASS_D', name='recyclabilityclass'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('productenvironmental',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('carbon_footprint_kg_co2e', sa.Float(), nullable=True),
    sa.Column('water_usage_liters', sa.Float(), nullable=True),
    sa.Column('energy_consumption_mj', sa.Float(), nullable=True),
    sa.Column('microplastic_shedding_rate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('substances_of_concern_present', sa.Boolean(), nullable=False),
    sa.Column('soc_declaration_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('productmateriallink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('is_recycled', sa.Boolean(), nullable=False),
    sa.Column('origin_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'material_id')
    )
    op.create_table('productsupplierlink',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('TIER_1_ASSEMBLY', 'TIER_2_FABRIC', 'TIER_3_FIBER', name='supplierrole'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'supplier_id')
    )
    op.create_table('sparepart',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('part_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordering_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sparepart')
    op.drop_table('productsupplierlink')
    op.drop_table('productmateriallink')
    op.drop_table('productenvironmental')
    op.drop_table('productdurability')
    op.drop_table('productcertificationlink')
    op.drop_index(op.f('ix_supplier_tenant_id'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_location_country'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_product_tenant_id'), table_name='product')
    op.drop_index(op.f('ix_product_model_reference'), table_name='product')
    op.drop_index(op.f('ix_product_gtin'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_material_name'), table_name='material')
    op.drop_index(op.f('ix_material_code'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_certification_code'), table_name='certification')
    op.drop_table('certification')
    # ### end Alembic commands ###
