"""add energy and water fields

Revision ID: 68a4ef7fc0db
Revises: 893fddaabd53
Create Date: 2026-01-16 21:51:56.754627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '68a4ef7fc0db'
down_revision: Union[str, Sequence[str], None] = '893fddaabd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_dpp_default_version', 'dpp', 'dppversion', [
                          'default_dpp_version_id'], ['id'], use_alter=True)
    op.add_column('productversion', sa.Column(
        'total_energy_mj', sa.Float(), nullable=True))
    op.add_column('productversion', sa.Column(
        'total_water_usage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productversion', 'total_water_usage')
    op.drop_column('productversion', 'total_energy_mj')
    op.drop_constraint('fk_dpp_default_version', 'dpp', type_='foreignkey')
    # ### end Alembic commands ###
