"""add product version field

Revision ID: b89f0a5a89c6
Revises: fe89e9b653c1
Create Date: 2026-01-14 21:17:29.165813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b89f0a5a89c6'
down_revision: Union[str, Sequence[str], None] = 'fe89e9b653c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('pending_version_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'pending_version_name')
    # ### end Alembic commands ###
