"""Add revision to ProductVersion

Revision ID: cb0149bf40d3
Revises: 5ec4e4399d98
Create Date: 2026-02-01 15:51:11.442900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb0149bf40d3'
down_revision: Union[str, Sequence[str], None] = '5ec4e4399d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_dpp_default_version', 'dpp', 'dppversion', ['default_dpp_version_id'], ['id'], use_alter=True)
    op.add_column('productversion', sa.Column('revision', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productversion', 'revision')
    op.drop_constraint('fk_dpp_default_version', 'dpp', type_='foreignkey')
    # ### end Alembic commands ###
