"""add file size in bytes field

Revision ID: dc98e7b883ec
Revises: 615962053c1e
Create Date: 2026-02-04 21:34:13.032891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc98e7b883ec'
down_revision: Union[str, Sequence[str], None] = '615962053c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productversioncertificate', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productversioncertificate', 'file_size_bytes')
    # ### end Alembic commands ###
