"""add 'transport_method' field

Revision ID: dff30ceec44f
Revises: 68a4ef7fc0db
Create Date: 2026-01-19 20:26:37.722090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dff30ceec44f'
down_revision: Union[str, Sequence[str], None] = '68a4ef7fc0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('productversionmaterial', sa.Column(
        'transport_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productversionmaterial', 'transport_method')
    op.alter_column('productversion', 'total_water_usage',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.alter_column('productversion', 'total_energy_mj',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    # ### end Alembic commands ###
