"""Add retry_count field in the TenantConnnection

Revision ID: fe89e9b653c1
Revises: 32659ce6b0f6
Create Date: 2026-01-13 23:26:02.941010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe89e9b653c1'
down_revision: Union[str, Sequence[str], None] = '32659ce6b0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_dpp_default_version', 'dpp', 'dppversion', ['default_dpp_version_id'], ['id'], use_alter=True)
    op.add_column('tenantconnection', sa.Column('retry_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenantconnection', 'retry_count')
    op.drop_constraint('fk_dpp_default_version', 'dpp', type_='foreignkey')
    # ### end Alembic commands ###
